version: '3'

services:
  fencing-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - FENCING_API_BASE_URL=${FENCING_API_BASE_URL:-https://yyfencing.oss-cn-beijing.aliyuncs.com/fencingscore}
    restart: unless-stopped
